package com.element.androidwebserver;

public class Pages {
    public static String HOMEPAGE = org.apache.commons.lang.StringUtils.join( new String[] {
            "<!DOCTYPE html>\n",

            "    <head>\n",
            "        <meta charset=\"utf-8\">\n",
            "        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\n",
            "                <title>Siloam Hospitals - Rumah Sakit Siloam Hospitals</title>\n",
            "              \n",
            "        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n",
            "        <meta name=\"google-site-verification\" content=\"aoCshxuaGQdU9xPlkS_FO5-QbXoKWnUIUmHsng-DwTU\" />\n",
            "        <meta name=\"google-site-verification\" content=\"Ko-LTnX-pLm7LdgJJZa6U7RbCJYJVNqrzR6nThKy75M\" />\n",
            "        <meta name=\"keywords\" content=\"rumah sakit, unit gawat darurat, hospital, jantung, rumah sakit indonesia, asma, dokter, suster, gawat darurat, emergency room, UGD, ER, \n",
            "                 Rumah Sakit Siloam di Jakarta, \n",
            "                  ambulan, ambulance, 24 jam, instalasi gawat darurat, kanker, sakit jantung, kecelakaan, otak, rumah sakit kanker, sakit jantung jakarta, dokter jantung, dokter syaraf, ambulans jakarta , gawat darurat jakarta, dokter ginjal, dokter urologi, dokter tulang, medical check up jakarta, sakit tulang jakarta, sakit ginjal jakarta, sakit syaraf jakarta, rumah sakit terbesar di jakarta, rumah sakit kanker di Indonesia, rumah sakit jantung jakarta, dokter jantung jakarta, dokter syaraf jakarta, ambulans gratis di jakarta, nomor gawat darurat jakarta, dokter ginjal jakarta, dokter urologi jakarta, dokter tulang jakarta, operasi bypass jantung, medical check up jakarta bagus, rumah sakit tulang terbaik di jakarta, dokter sakit ginjal di jakarta, rumah sakit syaraf di jakarta, rumah sakit terbaik di jakarta, rumah sakit kanker di jakarta, rumah sakit jantung terbaik di jakarta, dokter jantung terbaik, dokter syaraf terbaik, nomor ambulans jakarta, nomor gawat darurat jakarta, dokter ginjal terbaik, dokter urologi terbaik, dokter tulang jakarta terbaik, risiko operasi jantung, medical check up terbaik di jakarta, rumah sakit ortopedi terbaik di jakarta, rumah sakit ginjal di jakarta, dokter ahli sakit syaraf jakarta, rumah sakit bagus di jakarta, rumah sakit kanker terbaik, rumah sakit jantung jakarta yang bagus, dokter jantung terkenal, dokter syaraf terkenal, telepon ambulans jakarta, telepon gawat darurat jakarta, dokter ginjal terkenal, dokter urologi terkenal, dokter tulang terkenal, dokter operasi jantung, paket medical check up, dokter untuk sakit tulang di jakarta, dokter spesialis sakit ginjal di jakarta, spesialis sakit syaraf di jakarta, rumah sakit di jakarta selatan, rumah sakit kanker paling bagus, dokter spesialis jantung, dokter spesialis syaraf, UGD jakarta, dokter spesialis ginjal, dokter spesialis urologi, dokter spesialis tulang, dokter transplantasi ginjal, dokter penyakit tulang\n",
            "        \">\n",
            "        \n",
            "               <meta name=\"description\" content=\"Siloam Hospitals rumah sakit penyedia kesehatan terbesar di Indonesia, Menetapkan Standar Baru dalam Pelayanan Kesehatan, Kami adalah Rekan Kesehatan Anda\"/>\n",
            "        \n",
            "         \n",
            "          <meta property=\"og:title\" content=\"\" /> \n",
            "         \t<meta property=\"og:description\" content=\"\" /> \n",
            "\t\t<meta property=\"og:image\" content=\"https://www.siloamhospitals.com/admin/assets/uploads/\">\n",
            "        \n",
            "        \n",
            "        <link rel=\"mask-icon\" href=\"https://www.siloamhospitals.com/assets/favicon/siloam-icon-white.svg\" color=\"green\">\n",
            "        <link rel=\"icon\" sizes=\"any\" mask href=\"https://www.siloamhospitals.com/assets/favicon/siloam-icon-white.svg\">\n",
            "\t\t<meta name=\"theme-color\" content=\"#39a216\">\n",
            "\n",
            "        <link href=\"https://www.siloamhospitals.com/?ID\" rel=\"parent\" rev=\"subsection\" hreflang=\"id\">\n",
            "         <link href=\"https://www.siloamhospitals.com/?EN\" rel=\"parent\" rev=\"subsection\" hreflang=\"en\">\n",
            "         <link href=”https://plus.google.com/115607612008825012845/” rel=\"publisher\" />\n",
            "         <link rel=\"sitemap\" type=\"application/xml\" title=\"Sitemap\" href=\"https://www.siloamhospitals.com//admin/assets/uploads/siloam-sitemap.xml\" />\n",
            "        <!--link rel=\"apple-touch-icon-precomposed\" sizes=\"144x144\" href=\"apple-touch-icon-precomposed\"-->\n",
            "        \n",
            "         <link rel=\"apple-touch-icon\" href=\"https://www.siloamhospitals.com/assets/favicon/apple-touch-icon.png\" >\n",
            "        <link rel=\"shortcut icon\" href=\"https://www.siloamhospitals.com/assets/favicon/favicon.ico\">\n",
            "<link rel=\"stylesheet\" href=\"https://www.siloamhospitals.com/assets/css/w3.css\">\n",
            "\n",
            "        <link rel=\"stylesheet\" href=\"https://www.siloamhospitals.com/assets/css/bootstrap.css\">\n",
            "        <link rel=\"stylesheet\" href=\"https://www.siloamhospitals.com/assets/css/bootstrap-select.css\">\n",
            "        <link rel=\"stylesheet\" href=\"https://www.siloamhospitals.com/assets/css/stylesheets/main.css?a\">\n",
            "        <link rel=\"stylesheet\" href=\"https://www.siloamhospitals.com/assets/css/font-awesome.css\">\n",
            "        <link rel=\"stylesheet\" href=\"https://www.siloamhospitals.com/assets/css/jquery.bxslider.css\">\n",
            "        <link rel=\"stylesheet\" href=\"https://www.siloamhospitals.com/assets/css/custom.css?a\">\n",
            "        <link rel=\"stylesheet\" href=\"https://www.siloamhospitals.com/assets/css/typeahead.css\">\n",
            "        <link rel=\"stylesheet\" href=\"https://www.siloamhospitals.com/assets/css/home.css?time\">\n",
            "        <script src=\"https://www.siloamhospitals.com/assets/js/vendor/modernizr-2.6.2-respond-1.1.0.min.js\"></script>\n",
            "       <!-- <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js\"></script>-->\n",
            "\t\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js\"></script>\n",
            "<!--<script   src=\"https://code.jquery.com/jquery-3.1.1.min.js\"   integrity=\"sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=\"   crossorigin=\"anonymous\"></script> -->\n",
            "\t    <script>\n",
            "\t\t  (function() {\n",
            "\t\t    var cx = '012665678523307395344:xflhzx84due';\n",
            "\t\t    var gcse = document.createElement('script');\n",
            "\t\t    gcse.type = 'text/javascript';\n",
            "\t\t    gcse.async = true;\n",
            "\t\t    gcse.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') ,\n",
            "\t\t        '//cse.google.com/cse.js?cx=' , cx;\n",
            "\t\t    var s = document.getElementsByTagName('script')[0];\n",
            "\t\t    s.parentNode.insertBefore(gcse, s);\n",
            "\t\t  })();\n",
            "\t\t</script>\n",
            "\t\t<script>\n",
            "\t\t  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){\n",
            "\t\t  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),\n",
            "\t\t  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)\n",
            "\t\t  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');\n",
            "\t\t\n",
            "\t\t  ga('create', 'UA-74440366-1', 'auto');\n",
            "\t\t  ga('send', 'pageview');\n",
            "\t\t\n",
            "\t\t</script>\n",
            "\t\t\n",
            "\t\t<!-- Start Alexa Certify Javascript -->\n",
            "\t\t<script type=\"text/javascript\">\n",
            "\t\t_atrk_opts = { atrk_acct:\"JXMuj1aEsk00qg\", domain:\"siloamhospitals.com\",dynamic: true};\n",
            "\t\t(function() { var as = document.createElement('script'); as.type = 'text/javascript'; as.async = true; as.src = \"https://d31qbv1cthcecs.cloudfront.net/atrk.js\"; var s = document.getElementsByTagName('script')[0];s.parentNode.insertBefore(as, s); })();\n",
            "\t\t</script>\n",
            "\t\t<noscript><img src=\"https://d5nxst8fruw4z.cloudfront.net/atrk.gif?account=JXMuj1aEsk00qg\" style=\"display:none\" height=\"1\" width=\"1\" alt=\"\" /></noscript>\n",
            "\t\t<!-- End Alexa Certify Javascript -->  \t\t\n",
            "\t\t\n",
            "<!--<script type=\"text/javascript\" src=\"https://www.siloamhospitals.com/assets/js/css3-animate-it.js\"></script>-->\n",
            "<link href=\"https://www.siloamhospitals.com/assets/css/animated.css\" rel=\"stylesheet\" type=\"text/css\">\n",
            "          \n",
            "       \n",
            "    </head>\n",
            "    <body class=\"main-page\">\n",
            "\t    <!-- Start Facebook App -->\n",
            "\t      <script>\n",
            "\t\t  window.fbAsyncInit = function() {\n",
            "\t\t    FB.init({\n",
            "\t\t      appId      : '1123901120997935',\n",
            "\t\t      xfbml      : true,\n",
            "\t\t      version    : 'v2.7'\n",
            "\t\t    });\n",
            "\t\t\n",
            "\t\t    // ADD ADDITIONAL FACEBOOK CODE HERE\n",
            "\t\t    function onLogin(response) {\n",
            "\t\t\t  if (response.status == 'connected') {\n",
            "\t\t\t    FB.api('/me?fields=first_name', function(data) {\n",
            "\t\t\t      var welcomeBlock = document.getElementById('fb-welcome');\n",
            "\t\t\t      welcomeBlock.innerHTML = 'Hello, ' , data.first_name , '!';\n",
            "\t\t\t    });\n",
            "\t\t\t  }\n",
            "\t\t\t}\n",
            "\t\t\t\n",
            "\t\t\tFB.getLoginStatus(function(response) {\n",
            "\t\t\t  // Check login status on load, and if the user is\n",
            "\t\t\t  // already logged in, go directly to the welcome message.\n",
            "\t\t\t  if (response.status == 'connected') {\n",
            "\t\t\t    onLogin(response);\n",
            "\t\t\t  } else {\n",
            "\t\t\t    // Otherwise, show Login dialog first.\n",
            "\t\t\t    FB.login(function(response) {\n",
            "\t\t\t      onLogin(response);\n",
            "\t\t\t    }, {scope: 'user_friends, email'});\n",
            "\t\t\t  }\n",
            "\t\t\t});\n",
            "\t\t  };\n",
            "\t\t\n",
            "\t\t  (function(d, s, id){\n",
            "\t\t     var js, fjs = d.getElementsByTagName(s)[0];\n",
            "\t\t     if (d.getElementById(id)) {return;}\n",
            "\t\t     js = d.createElement(s); js.id = id;\n",
            "\t\t     js.src = \"//connect.facebook.net/en_US/sdk.js\";\n",
            "\t\t     fjs.parentNode.insertBefore(js, fjs);\n",
            "\t\t   }(document, 'script', 'facebook-jssdk'));\n",
            "\t\t   \n",
            "\t\t   \n",
            "\t\t   \n",
            "\t\t</script>\n",
            "\t\t\n",
            "\t    <!-- End Facebook App --> \n",
            "\t    \n",
            "\t    <h1 id=\"fb-welcome\"></h1>\n",
            "    \t<!--[if lt IE 7]>\n",
            "            <p class=\"browsehappy\">You are using an <strong>outdated</strong> browser. Please <a href=\"http://browsehappy.com/\">upgrade your browser</a> to improve your experience.</p>\n",
            "        <![endif]-->\n",
            "              <div class=\"main-wrapper\">\n",
            "        <ul id=\"navbar-wrapper\">\n",
            "        \t        \t            <li><a href=\"https://www.siloamhospitals.com/?EN\">Home</a>\n",
            "            \t            </li>\n",
            "           \t            <li><a href=\"https://www.siloamhospitals.com/our-hospitals.html?EN\">Our Hospitals</a>\n",
            "            \t            \t<ul class=\"our-hospitals\">\n",
            "            \t\t            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-hospitals/read/bimc-hospital-nusa-dua.html\">BIMC Hospital Nusa Dua</a></li>\n",
            "            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-hospitals/read/siloam-hospitals-jambi.html\">Siloam Hospitals Jambi</a></li>\n",
            "            \t\t\t            \t\t\t            \t\t            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-hospitals/read/bimc-kuta.html\">BIMC KUTA</a></li>\n",
            "            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-hospitals/read/siloam-hospitals-jogjakarta.html\">Siloam Hospitals Jogjakarta</a></li>\n",
            "            \t\t\t            \t\t\t            \t\t            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-hospitals/read/mrccc-siloam-hospitals-semanggi.html\">MRCCC Siloam Hospitals Semanggi </a></li>\n",
            "            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-hospitals/read/siloam-hospitals-kebon-jeruk.html\">Siloam Hospitals Kebon Jeruk</a></li>\n",
            "            \t\t\t            \t\t\t            \t\t            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-hospitals/read/rumah-sakit-umum-siloam.html\">Paviliun Umum Rumah Sakit Siloam</a></li>\n",
            "            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-hospitals/read/siloam-hospitals-kupang.html\">Siloam Hospitals Kupang</a></li>\n",
            "            \t\t\t            \t\t\t            \t\t            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-hospitals/read/rumah-sakit-asri.html\">Rumah Sakit ASRI</a></li>\n",
            "            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-hospitals/read/siloam-hospitals-labuan-bajo.html\">Siloam Hospitals Labuan Bajo</a></li>\n",
            "            \t\t\t            \t\t\t            \t\t            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-hospitals/read/grha-ultima-medika-hospital-rs-gum-2.html\">Rumah Sakit Grha Utima Medika (Mataram)</a></li>\n",
            "            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-hospitals/read/siloam-hospitals-lippo-cikarang.html\">Siloam Hospitals Lippo Cikarang</a></li>\n",
            "            \t\t\t            \t\t\t            \t\t            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-hospitals/read/rumah-sakit-putera-bahagia-cirebon.html\">Rumah Sakit Putera Bahagia (Cirebon)</a></li>\n",
            "            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-hospitals/read/siloam-hospitals-lippo-village.html\">Siloam Hospitals Lippo Village</a></li>\n",
            "            \t\t\t            \t\t\t            \t\t            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-hospitals/read/sdasdasd.html\">Rumah Sakit Sentosa</a></li>\n",
            "            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-hospitals/read/siloam-hospitals-makassar.html\">Siloam Hospitals Makassar</a></li>\n",
            "            \t\t\t            \t\t\t            \t\t            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-hospitals/read/siloam-hospitals-bangka-belitung.html\">Rumah Sakit Siloam Bangka</a></li>\n",
            "            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-hospitals/read/siloam-hospitals-manado.html\">Siloam Hospitals Manado</a></li>\n",
            "            \t\t\t            \t\t\t            \t\t            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-hospitals/read/rumah-sakit-siloam-silampari.html\">Rumah Sakit Siloam Silampari</a></li>\n",
            "            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-hospitals/read/siloam-hospitals-medan.html\">Siloam Hospitals Medan</a></li>\n",
            "            \t\t\t            \t\t\t            \t\t            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-hospitals/read/siloam-hospital-canggu.html\">Siloam Canggu</a></li>\n",
            "            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-hospitals/read/siloam-hospitals-purwakarta.html\">Siloam Hospitals Purwakarta</a></li>\n",
            "            \t\t\t            \t\t\t            \t\t            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-hospitals/read/siloam-hospital-jember.html\">Siloam Hospital Jember</a></li>\n",
            "            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-hospitals/read/siloam-hospitals-surabaya.html\">Siloam Hospitals Surabaya</a></li>\n",
            "            \t\t\t            \t\t\t            \t\t            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-hospitals/read/siloam-hospitals-balikpapan.html\">Siloam Hospitals Balikpapan</a></li>\n",
            "            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-hospitals/read/siloam-hospitals-tb-simatupang.html\">Siloam Hospitals TB Simatupang</a></li>\n",
            "            \t\t\t            \t\t\t            \t\t            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-hospitals/read/siloam-hospitals-bogor.html\">Siloam Hospitals Bogor</a></li>\n",
            "            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-hospitals/read/siloam-medika-blu-plaza.html\">Siloam Medika Blu Plaza</a></li>\n",
            "            \t\t\t            \t\t\t            \t\t            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-hospitals/read/siloam-hospitals-buton.html\">Siloam Hospitals Buton</a></li>\n",
            "            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-hospitals/read/siloam-medika-samarinda.html\">Siloam Medika Samarinda</a></li>\n",
            "            \t\t\t            \t\t\t            \t\t            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-hospitals/read/siloam-hospitals-cinere.html\">Siloam Hospitals Cinere</a></li>\n",
            "            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-hospitals/read/siloam-sriwijaya-palembang.html\">Siloam Sriwijaya Palembang</a></li>\n",
            "            \t\t\t            \t\t\t            \t\t            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-hospitals/read/siloam-hospitals-denpasar.html\">Siloam Hospitals Denpasar</a></li>\n",
            "            \t\t\t            \t\t\t            \t\t            \t\t\t            \t\t            \t\t\t            \t\t            \t\t\t            \t\t            \t\t\t            \t\t            \t\t\t            \t\t            \t\t\t            \t\t            \t\t\t            \t\t            \t\t\t            \t\t            \t\t\t            \t\t            \t\t\t            \t\t            \t\t\t            \t\t            \t\t\t            \t\t            \t\t\t            \t\t            \t\t\t            \t\t            \t\t\t            \t\t            \t\t\t            \t\t \n",
            "            \t</ul>\n",
            "            \t            </li>\n",
            "           \t            <li><a href=\"https://www.siloamhospitals.com/our-specialties.html?EN\">Our Specialties</a>\n",
            "            \t            \t<ul class=\"our-specialties\">\n",
            "            \t\t            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-specialties/bones-orthopaedics.html\">Bones (Orthopaedics)</a></li>\n",
            "            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-specialties/heart-vascular-cardiology.html\">Heart & Vascular (Cardiology)</a></li>\n",
            "            \t\t\t            \t\t\t            \t\t            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-specialties/brain-nerve-neurosciences.html\">Brain & Nerve (Neurosciences)</a></li>\n",
            "            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-specialties/internal-medicine.html\">Internal Medicine</a></li>\n",
            "            \t\t\t            \t\t\t            \t\t            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-specialties/cancer-oncology.html\">Cancer (Oncology)</a></li>\n",
            "            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-specialties/kidneys-nephrology.html\">Kidneys (Nephrology)</a></li>\n",
            "            \t\t\t            \t\t\t            \t\t            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-specialties/children-paediatrics.html\">Children (Paediatrics)</a></li>\n",
            "            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-specialties/lungs-pulmonology-respiratory.html\">Lungs (Pulmonology/ Respiratory)</a></li>\n",
            "            \t\t\t            \t\t\t            \t\t            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-specialties/ear-nose-throat-otolaryngology.html\">Ear, Nose, & Throat (Otolaryngology)</a></li>\n",
            "            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-specialties/other-specialties.html\">Other Specialties</a></li>\n",
            "            \t\t\t            \t\t\t            \t\t            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-specialties/emergency.html\">Emergency</a></li>\n",
            "            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-specialties/stomach-digestive-system-gastroenterology.html\">Stomach & Digestive System (Gastroenterology)</a></li>\n",
            "            \t\t\t            \t\t\t            \t\t            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-specialties/eyes-ophthalmology.html\">Eyes (Ophthalmology)</a></li>\n",
            "            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-specialties/urinary-reproductive-system-urology.html\">Urinary & Reproductive System (Urology)</a></li>\n",
            "            \t\t\t            \t\t\t            \t\t            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-specialties/general-surgery.html\">General Surgery</a></li>\n",
            "            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/our-specialties/women-obstetrics-gynaecology.html\">Women (Obstetrics & Gynaecology)</a></li>\n",
            "            \t\t\t            \t\t\t            \t\t            \t\t\t            \t\t            \t\t\t            \t\t            \t\t\t            \t\t            \t\t\t            \t\t            \t\t\t            \t\t            \t\t\t            \t\t            \t\t\t            \t\t            \t\t\t            \t\t \n",
            "            \t</ul>\n",
            "            \t            </li>\n",
            "           \t            <li><a href=\"https://www.siloamhospitals.com/plan-your-visit.html?EN\">Plan Your Visit</a>\n",
            "            \t            \t<ul class=\"plan-your-visit\">\n",
            "            \t\t            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/plan-your-visit/admission-information.html?#admission-information\">Admission Information</a></li>\n",
            "            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/plan-your-visit/dining-options.html?#dining-options\">Dining Options</a></li>\n",
            "            \t\t\t            \t\t\t            \t\t            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/plan-your-visit/ambulance-special-transport.html?#ambulance-special-transport\">Ambulance & Special Transport</a></li>\n",
            "            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/plan-your-visit/wifi.html?#wifi\">WiFi</a></li>\n",
            "            \t\t\t            \t\t\t            \t\t            \t\t\t            \t\t\t<li><a href=\"https://www.siloamhospitals.com/plan-your-visit/accommodations-nearby.html?#accommodations-nearby\">Accommodations Nearby</a></li>\n",
            "            \t\t\t            \t\t\t            \t\t            \t\t\t            \t\t            \t\t\t            \t\t \n",
            "            \t</ul>\n",
            "            \t            </li>\n",
            "           \t            <li><a href=\"https://www.siloamhospitals.com/news-events/media-coverage.html?EN\">Media Coverage</a>\n",
            "            \t            </li>\n",
            "           \t            <li><a href=\"https://www.siloamhospitals.com/career.html?EN\">Career With Us</a>\n",
            "            \t            </li>\n",
            "           \t           \t<li class=\"visible-xs visible-xs\"><a href=\"https://www.siloamhospitals.com/contact-us.html\">Contact Us</a></li>\n",
            "           \t<li class=\"visible-xs visible-xs\"><a href=\"https://www.siloamhospitals.com/faq.html\">FAQ</a></li>\n",
            "           \t<li class=\"visible-xs visible-xs\"><a href=\"https://www.siloamhospitals.com/ecard.html\">Send E-card</a></li>\n",
            "        </ul>\n",
            "        <div class=\"overlay-close\"></div>\n",
            "        <header>\n",
            "          <div class=\"container\">\n",
            "          <div class=\"header-wrapper row\">\n",
            "             <div id=\"navbar\" class=\"navbar-collapse collapse\">\n",
            "                  <div class=\"pull-left col-md-3\">\n",
            "                     <a class=\"nav-toggle\" data-target=\"#navbar-wrapper\">\n",
            "                      <span class=\"icon-bar\"></span>\n",
            "                      <span class=\"icon-bar\"></span>\n",
            "                      <span class=\"icon-bar\"></span>\n",
            "                      <span class=\"nav-txt\">MENU</span>\n",
            "                    </a>\n",
            "                    <a class=\"logo\" href=\"https://www.siloamhospitals.com/\">\n",
            "                      <img src=\"https://www.siloamhospitals.com/assets/img/logo.png\">\n",
            "                    </a>\n",
            "                  </div>\n",
            "                  <div class=\"pull-right col-md-9\">\n",
            "                    <div class=\"lang_select dropdown\">\n",
            "                    \t                      \t<a href=\"https://www.siloamhospitals.com/?EN\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-expanded=\"false\">EN <i class=\"fa fa-caret-down\"></i></a>\n",
            "                      \t<ul class=\"dropdown-menu\" role=\"menu\">\n",
            "                        \t<li><a href=\"https://www.siloamhospitals.com/?ID\">ID</a></li>\n",
            "                      \t</ul>\n",
            "                    \t                    </div>\n",
            "                    <form class=\"top_search\" action=\"/search\">\n",
            "\t\t\t\t\t  <input id=\"q\" name=\"q\" placeholder=\"Search Here\" type=\"text\"/>\n",
            "                      <button>\n",
            "                        <i class=\"fa fa-search\"></i>\n",
            "                      </button>\n",
            "                    </form>\n",
            "                    <a class=\"location_toggle\" href=\"https://www.siloamhospitals.com/find-nearest-hospital.html\">\n",
            "                      <span class=\"nav-txt\">FIND NEAREST HOSPITAL</span>\n",
            "                      <i class=\"fa fa-map-marker\"></i>\n",
            "                    </a>\n",
            "                    <div class=\"socio-top\">\n",
            "                      <a href=\"https://www.facebook.com/siloamhospitalsgroup\" target=\"_blank\">\n",
            "                        <i class=\"fa fa-facebook\"></i>\n",
            "                      </a>\n",
            "                      <a href=\"https://www.instagram.com/siloamhospitals/?hl=en\" target=\"_blank\">\n",
            "                        <i class=\"fa fa-instagram\"></i>\n",
            "                      </a>\n",
            "                    </div>\n",
            "                  </div>\n",
            "                </div>\n",
            "            </div>\n",
            "          </div>\n",
            "          <div class=\"sidebar hidden-xs\">\n",
            "          \t            <div class=\"emergency\"> <a href=\"tel:,62-1500911\"><span>1500911</span></a> </div>\n",
            "                  \t                <div class=\"find_doctor\">\n",
            "              <a id=\"find_toggle\"></a>\n",
            "                            <div class=\"wrapper\">\n",
            "                  <div class=\"inwrap dark\">\n",
            "                  <div class=\"title\"><!--<h3>Find Your Doctors</h3>--></div>\n",
            "                  <div class=\"selection\">\n",
            "                  <form class=\"default_input find-doctor\" action=\"https://www.siloamhospitals.com/doctors/find.html\" method=\"GET\">\n",
            "                  \t<select name=\"hospital\" class=\"custom_select\" data-live-search=\"false\">\n",
            "                      <option value=\"\">Select a Hospital</option>\n",
            "                                                                  \t<option value=\"10\">BIMC Hospital Nusa Dua</option>\n",
            "                                            \t<option value=\"26\">BIMC KUTA</option>\n",
            "                                            \t<option value=\"13\">MRCCC Siloam Hospitals Semanggi </option>\n",
            "                                            \t<option value=\"27\">Paviliun Umum Rumah Sakit Siloam</option>\n",
            "                                            \t<option value=\"15\">Rumah Sakit ASRI</option>\n",
            "                                            \t<option value=\"979\">Rumah Sakit Grha Utima Medika (Mataram)</option>\n",
            "                                            \t<option value=\"1095\">Rumah Sakit Putera Bahagia (Cirebon)</option>\n",
            "                                            \t<option value=\"1052\">Rumah Sakit Sentosa</option>\n",
            "                                            \t<option value=\"912\">Rumah Sakit Siloam Bangka</option>\n",
            "                                            \t<option value=\"1109\">Rumah Sakit Siloam Silampari</option>\n",
            "                                            \t<option value=\"850\">Siloam Canggu</option>\n",
            "                                            \t<option value=\"1105\">Siloam Hospital Jember</option>\n",
            "                                            \t<option value=\"24\">Siloam Hospitals Balikpapan</option>\n",
            "                                            \t<option value=\"744\">Siloam Hospitals Bogor</option>\n",
            "                                            \t<option value=\"648\">Siloam Hospitals Buton</option>\n",
            "                                            \t<option value=\"14\">Siloam Hospitals Cinere</option>\n",
            "                                            \t<option value=\"25\">Siloam Hospitals Denpasar</option>\n",
            "                                            \t<option value=\"22\">Siloam Hospitals Jambi</option>\n",
            "                                            \t<option value=\"1068\">Siloam Hospitals Jogjakarta</option>\n",
            "                                            \t<option value=\"12\">Siloam Hospitals Kebon Jeruk</option>\n",
            "                                            \t<option value=\"42\">Siloam Hospitals Kupang</option>\n",
            "                                            \t<option value=\"673\">Siloam Hospitals Labuan Bajo</option>\n",
            "                                            \t<option value=\"17\">Siloam Hospitals Lippo Cikarang</option>\n",
            "                                            \t<option value=\"8\">Siloam Hospitals Lippo Village</option>\n",
            "                                            \t<option value=\"18\">Siloam Hospitals Makassar</option>\n",
            "                                            \t<option value=\"19\">Siloam Hospitals Manado</option>\n",
            "                                            \t<option value=\"20\">Siloam Hospitals Medan</option>\n",
            "                                            \t<option value=\"21\">Siloam Hospitals Purwakarta</option>\n",
            "                                            \t<option value=\"6\">Siloam Hospitals Surabaya</option>\n",
            "                                            \t<option value=\"16\">Siloam Hospitals TB Simatupang</option>\n",
            "                                            \t<option value=\"699\">Siloam Medika Blu Plaza</option>\n",
            "                                            \t<option value=\"714\">Siloam Medika Samarinda</option>\n",
            "                                            \t<option value=\"23\">Siloam Sriwijaya Palembang</option>\n",
            "                                          </select>\n",
            "                    <select name=\"specialties\" class=\"custom_select\" data-live-search=\"false\">\n",
            "                      <option value=\"\">Select Specialties</option>\n",
            "                                                                  \t<option value=\"35\">Acupuncture</option>\n",
            "                                            \t<option value=\"67\">Allergy & Immunologist</option>\n",
            "                                            \t<option value=\"45\">Anaesthetic</option>\n",
            "                                            \t<option value=\"54\">Anatomical Pathologist</option>\n",
            "                                            \t<option value=\"41\">Andrologi</option>\n",
            "                                            \t<option value=\"7\">Cardio Thoraric & Vascular Surgeon</option>\n",
            "                                            \t<option value=\"16\">Cardiologist</option>\n",
            "                                            \t<option value=\"60\">Clinical Microbiologist</option>\n",
            "                                            \t<option value=\"48\">Clinical Pathologist</option>\n",
            "                                            \t<option value=\"17\">Dentist</option>\n",
            "                                            \t<option value=\"58\">Dentist - Pediatric Consultant</option>\n",
            "                                            \t<option value=\"23\">Dermato-Venerologist</option>\n",
            "                                            \t<option value=\"43\">Diabetic Clinic</option>\n",
            "                                            \t<option value=\"8\">Digestive Surgeon</option>\n",
            "                                            \t<option value=\"18\">Endodontist</option>\n",
            "                                            \t<option value=\"33\">ENT/THT</option>\n",
            "                                            \t<option value=\"37\">Esthetiderma</option>\n",
            "                                            \t<option value=\"38\">General Practitioner</option>\n",
            "                                            \t<option value=\"24\">Geneticist</option>\n",
            "                                            \t<option value=\"25\">Internist</option>\n",
            "                                            \t<option value=\"50\">Internist  Nephorologist</option>\n",
            "                                            \t<option value=\"57\">Internist - Hematology & Oncology Consultant</option>\n",
            "                                            \t<option value=\"53\">Internist Cardiologist</option>\n",
            "                                            \t<option value=\"52\">Internist Endocrinologist</option>\n",
            "                                            \t<option value=\"49\">Internist Gastroenterology Hepatology</option>\n",
            "                                            \t<option value=\"28\">Internist Pulmonologist</option>\n",
            "                                            \t<option value=\"51\">Internist Tropical Infectious</option>\n",
            "                                            \t<option value=\"63\">Laboratory</option>\n",
            "                                            \t<option value=\"47\">Medical Oncology</option>\n",
            "                                            \t<option value=\"44\">Medical Rehabilitation</option>\n",
            "                                            \t<option value=\"36\">Memory Clinic</option>\n",
            "                                            \t<option value=\"39\">Multiple Sclerosis Clinic</option>\n",
            "                                            \t<option value=\"9\">Neuro Surgeon</option>\n",
            "                                            \t<option value=\"29\">Neurologist</option>\n",
            "                                            \t<option value=\"66\">Nuclear Medicine</option>\n",
            "                                            \t<option value=\"1\">Nutritionist</option>\n",
            "                                            \t<option value=\"26\">Obstetrician and Gynecologist</option>\n",
            "                                            \t<option value=\"59\">Obstetrician and Gynecologist - Oncology Consultant</option>\n",
            "                                            \t<option value=\"11\">Oncology Surgeon</option>\n",
            "                                            \t<option value=\"64\">One Day Care</option>\n",
            "                                            \t<option value=\"34\">Opthalmologist</option>\n",
            "                                            \t<option value=\"10\">Oral & Maxilla facial Surgeon</option>\n",
            "                                            \t<option value=\"19\">Oral.Medicine</option>\n",
            "                                            \t<option value=\"20\">Orthodontist</option>\n",
            "                                            \t<option value=\"61\">Orthopedic Surgeon</option>\n",
            "                                            \t<option value=\"62\">Orthopedic Surgeon - Hip Knee and Geriatric Trauma</option>\n",
            "                                            \t<option value=\"12\">Orthopedic Surgeon - Spine Consultant</option>\n",
            "                                            \t<option value=\"21\">Paedodontist</option>\n",
            "                                            \t<option value=\"3\">Pediatric Cardiologist</option>\n",
            "                                            \t<option value=\"4\">Pediatric Neurologist</option>\n",
            "                                            \t<option value=\"5\">Pediatric Surgeon</option>\n",
            "                                            \t<option value=\"2\">Pediatrician</option>\n",
            "                                            \t<option value=\"40\">Pedodontist</option>\n",
            "                                            \t<option value=\"22\">Periodontist</option>\n",
            "                                            \t<option value=\"55\">Phrosthodontist</option>\n",
            "                                            \t<option value=\"32\">Physiotherapist</option>\n",
            "                                            \t<option value=\"13\">Plastic & Reconstruction Surgeon</option>\n",
            "                                            \t<option value=\"30\">Psychiatrist</option>\n",
            "                                            \t<option value=\"31\">Psychologist</option>\n",
            "                                            \t<option value=\"27\">Pulmonologist</option>\n",
            "                                            \t<option value=\"65\">Radiation Oncology</option>\n",
            "                                            \t<option value=\"46\">Radiology</option>\n",
            "                                            \t<option value=\"14\">Spinal Surgeon</option>\n",
            "                                            \t<option value=\"6\">Surgeon</option>\n",
            "                                            \t<option value=\"56\">Surgeon - Orthopedics & Traumatology</option>\n",
            "                                            \t<option value=\"15\">Urologist</option>\n",
            "                                            \t<option value=\"42\">Wound Care Clinic</option>\n",
            "                                          </select>\n",
            "                    <input type=\"text\" placeholder=\"Type Doctor's Name\" name=\"doctor\" autocomplete=\"off\" />\n",
            "                    <!--select name=\"doctors\" class=\"custom_select\" data-live-search=\"true\">\n",
            "                      <option value=\"\">Type Doctor Name</option>\n",
            "                                                                </select-->\n",
            "                    <button class=\"btn submit\">\n",
            "                      Find                    </button>\n",
            "                  </form>\n",
            "                </div>\n",
            "              \t</div>\n",
            "       \t\t</div>\n",
            "   \t\t</div>\n",
            "      \t                  <div class=\"find_location\">\n",
            "                 <a id=\"find_location_toggle\"></a>\n",
            "                                  <div class=\"wrapper\">\n",
            "                        <div class=\"inwrap dark\" style=\"overflow-y: scroll; height: 100%\">\n",
            "                            <div class=\"title\"><!--<h3>Recently Visited</h3>--></div>\n",
            "                            <ul>\n",
            "                                                        \t<li><a href=\"https://www.siloamhospitals.com/\" style=\"color: #FFF\">Siloam Hospitals</a></li>\n",
            "                                                        </ul>\n",
            "                        </div>\n",
            "                    </div>\n",
            "              </div>\n",
            "          </div>\n",
            "        </header>\n",
            "        <div style=\"display: none;\">\n",
            "<!--\n",
            "\t        <h5>rumah sakit</h5>\n",
            "\t        <h5>unit gawat darurat</h5>\n",
            "          <h5>dokter syaraf </h5>\n",
            "\t\t\t<h5>rumah sakit indonesia</h5>\n",
            "\t\t\t<h5>rumah sakit terbesar</h5>\n",
            "\t\t\t<h5>rumah sakit terbaik</h5>\n",
            "\t\t\t<h5>rumah sakit kanker</h5>\n",
            "\t\t\t<h5>rumah sakit jakarta</h5>\n",
            "      <h5>sakit jantung jakarta</h5>\n",
            "\t\t\t<h5>rumah sakit bagus</h5>\n",
            "\t\t\t<h5>rumah sakit otak</h5>\n",
            "\t\t\t<h5>rumah sakit jantung</h5>\n",
            "\t\t\t<h5>jantung</h5>\n",
            "\t\t\t<h5>penyakit jantung</h5>\t\n",
            "\t\t\t<h5>perwatan jantung</h5>\n",
            "\t\t\t<h5>gejala jantung</h5>\t\n",
            "\t\t\t<h5>dokter jantung</h5>\t\t\t\n",
            "      <h5>ambulans jakarta</h5>\n",
            "      <h5>dokter ginjal</h5>\n",
            "      <h5>gawat darurat jakarta</h5>\n",
            "      <h5>dokter urologi</h5>\n",
            "      <h5>dokter tulang</h5>\n",
            "      <h5>operasi jantung</h5>\n",
            "      <h5>medical check up jakarta</h5>\n",
            "      <h5>sakit tulang jakarta</h5>\n",
            "      <h5>sakit ginjal jakarta</h5>\n",
            "      <h5>sakit syaraf jakarta</h5>\n",
            "-->\t\t\t        \n",
            "\t        \n",
            "<!--\n",
            "\t        <h1>\n",
            "\t       rumah sakit, unit gawat darurat, hospital, jantung, rumah sakit indonesia, asma, rumah sakit terbesar, rumah sakit terbaik, penyakit asma, dokter, suster, gejala asma, gejala darah tinggi, gawat darurat, emergency room, UGD, ER, rumah sakit jakarta, ambulan, ambulance, 24 jam, instalasi gawat darurat, kanker, otak, kecelakaan, skoliosis, rumah sakit kanker, sakit jantung jakarta, dokter jantung, dokter syaraf ,ambulans jakarta, gawat darurat jakarta, dokter ginjal, dokter urologi, dokter tulang, operasi jantung, medical check up jakarta, sakit tulang jakarta, sakit ginjal jakarta, sakit syaraf jakarta\n",
            "\t        </h1>\n",
            "\t        <h2>\n",
            "\t        rumah sakit, unit gawat darurat, hospital, jantung, rumah sakit indonesia, asma, rumah sakit terbesar, rumah sakit terbaik, penyakit asma, dokter, suster, gejala asma, gejala darah tinggi, gawat darurat, emergency room, UGD, ER, rumah sakit jakarta, ambulan, ambulance, 24 jam, instalasi gawat darurat, kanker, otak, kecelakaan, skoliosis, rumah sakit kanker, sakit jantung jakarta, dokter jantung, dokter syaraf ,ambulans jakarta, gawat darurat jakarta, dokter ginjal, dokter urologi, dokter tulang, operasi jantung, medical check up jakarta, sakit tulang jakarta, sakit ginjal jakarta, sakit syaraf jakarta\n",
            "\t        </h2>\n",
            "\t        <h3>\n",
            "\t       rumah sakit, unit gawat darurat, hospital, jantung, rumah sakit indonesia, asma, rumah sakit terbesar, rumah sakit terbaik, penyakit asma, dokter, suster, gejala asma, gejala darah tinggi, gawat darurat, emergency room, UGD, ER, rumah sakit jakarta, ambulan, ambulance, 24 jam, instalasi gawat darurat, kanker, otak, kecelakaan, skoliosis, rumah sakit kanker, sakit jantung jakarta, dokter jantung, dokter syaraf ,ambulans jakarta, gawat darurat jakarta, dokter ginjal, dokter urologi, dokter tulang, operasi jantung, medical check up jakarta, sakit tulang jakarta, sakit ginjal jakarta, sakit syaraf jakarta\n",
            "\t        </h3>\n",
            "\t        <title>\t        \n",
            "          rumah sakit, unit gawat darurat, hospital, jantung, rumah sakit indonesia, asma, rumah sakit terbesar, rumah sakit terbaik, penyakit asma, dokter, suster, gejala asma, gejala darah tinggi, gawat darurat, emergency room, UGD, ER, rumah sakit jakarta, ambulan, ambulance, 24 jam, instalasi gawat darurat, kanker, otak, kecelakaan, skoliosis, rumah sakit kanker, sakit jantung jakarta, dokter jantung, dokter syaraf ,ambulans jakarta, gawat darurat jakarta, dokter ginjal, dokter urologi, dokter tulang, operasi jantung, medical check up jakarta, sakit tulang jakarta, sakit ginjal jakarta, sakit syaraf jakarta\n",
            "\t        </title>\n",
            "-->\n",
            "        </div><!--\n",
            "<div\n",
            "  class=\"fb-like\"\n",
            "  data-share=\"true\"\n",
            "  data-width=\"450\"\n",
            "  data-show-faces=\"true\">\n",
            "</div>\n",
            "-->\n",
            "\n",
            "<div class=\"container-fluid\">\n",
            "  <div class=\"jumbotron row\" id=\"facility\">\n",
            "    <div class=\"top-img carousel slide carousel-fade\" data-ride=\"carousel\" id=\"home-slide\">\n",
            "    \t<div class=\"carousel-inner\" role=\"listbox\">\n",
            "    \t\t        \t<div class=\"item active\">\n",
            "        \t\t<img src=\"https://www.siloamhospitals.com/admin/assets/uploads/2017/08/welcome-to-siloam-hospitals2.jpg\">\n",
            "        \t\t<div class=\"caption\">\n",
            "        \t\t\t<h3>Welcome to Siloam Hospitals</h3>\n",
            "        \t\t\t<p>The Largest Healthcare Provider of Choice in Indonesia</p>\n",
            "        \t\t\t        \t\t</div>\n",
            "        \t</div>\n",
            "        \t        \t<div class=\"item \">\n",
            "        \t\t<img src=\"https://www.siloamhospitals.com/admin/assets/uploads/2017/18/number-emergency2.jpg\">\n",
            "        \t\t<div class=\"caption\">\n",
            "        \t\t\t<h3>Save This Number to Save Each Other</h3>\n",
            "        \t\t\t<p>Call us for any emergency cases</p>\n",
            "        \t\t\t        \t\t</div>\n",
            "        \t</div>\n",
            "        \t        \t<div class=\"item \">\n",
            "        \t\t<img src=\"https://www.siloamhospitals.com/admin/assets/uploads/2017/08/partner-in-healthcare.jpg\">\n",
            "        \t\t<div class=\"caption\">\n",
            "        \t\t\t<h3>Partner in Healthcare</h3>\n",
            "        \t\t\t<p>Our highly qualified team is ready to help you</p>\n",
            "        \t\t\t        \t\t</div>\n",
            "        \t</div>\n",
            "        \t        \t<div class=\"item \">\n",
            "        \t\t<img src=\"https://www.siloamhospitals.com/admin/assets/uploads/2017/02/send-personalised-cards.jpg\">\n",
            "        \t\t<div class=\"caption\">\n",
            "        \t\t\t<h3>Send Personalised Cards</h3>\n",
            "        \t\t\t<p>Let's show your loved ones how much you care</p>\n",
            "        \t\t\t\t\t\t\t\t<a href=\"http://www.siloamhospitals.com/ecard.html\" class=\"slide-link\">e-greeting</a>\n",
            "\t\t\t\t\t        \t\t</div>\n",
            "        \t</div>\n",
            "        \t        \t<div class=\"item \">\n",
            "        \t\t<img src=\"https://www.siloamhospitals.com/admin/assets/uploads/2017/18/HARDIKNAS SHJR-GrandOpeningAds-BannerWebsite2.jpg\">\n",
            "        \t\t<div class=\"caption\">\n",
            "        \t\t\t<h3>Bangsa Yang Sehat Untuk Masa Depan Yang Cerah</h3>\n",
            "        \t\t\t<p>Untuk informasi dan pendaftaran, hubungi 1-500-181</p>\n",
            "        \t\t\t        \t\t</div>\n",
            "        \t</div>\n",
            "        \t    \t</div>\n",
            "    \t<!-- Indicators -->\n",
            "\t\t<ol class=\"carousel-indicators\">\n",
            "    \t\t\t\t    <li data-target=\"#home-slide\" data-slide-to=\"0\" class=\"active\"></li>\n",
            "        \t\t\t    <li data-target=\"#home-slide\" data-slide-to=\"1\" class=\"\"></li>\n",
            "        \t\t\t    <li data-target=\"#home-slide\" data-slide-to=\"2\" class=\"\"></li>\n",
            "        \t\t\t    <li data-target=\"#home-slide\" data-slide-to=\"3\" class=\"\"></li>\n",
            "        \t\t\t    <li data-target=\"#home-slide\" data-slide-to=\"4\" class=\"\"></li>\n",
            "        \t\t\t</ol>\n",
            "\t\t<!-- End Indicator -->\n",
            "    </div>\n",
            "  </div>\n",
            "  \n",
            "  \n",
            "</div>\n",
            "\n",
            "\n",
            "\n",
            "<div class=\"container-fluid\"  id=\"centre-excellence\" style=\"min-height: 250px;\">\n",
            "  <section style=\"min-height: 250px;\">\n",
            "\t\t\t  <div class=\"row\">\n",
            "\t\t\t\t\t\t  <div class=\"col-md-2\">\n",
            "\t\t\t\t\t\t      <h2 class=\"title\">\n",
            "\t\t\t\t\t\t        Centres of Excellence\t\t\t\t\t\t      </h2>\n",
            "\t\t\t\t\t\t  </div>\n",
            "\t\t\t\t\t\t  <div class=\"col-md-10\">\n",
            "\t\t\t\t\t\t  \t\t<div id=\"excellence\" class=\"carousel slide carousel-slide\" data-ride=\"carousel\">\n",
            "\t\t\t    \t\t\t\t\t\t<ul class=\"bxslider\">\n",
            "\t\t\t\t\t\t\t\t\t \t\t\t\t\t\t\t\t\t\t  \t<li>\n",
            "\t\t\t\t\t\t\t\t\t\t\t  \t<a href=\"https://www.siloamhospitals.com/centre-of-excellence/cardiology.html?EN\">\n",
            "\t\t\t\t\t\t\t\t\t               <span>Cardiology</span>\n",
            "\t\t\t\t\t\t\t\t\t                <img width=\"100%\" class=\"imagecheck\" src=\"https://www.siloamhospitals.com/assets/img/no-pic.jpg\" data-src=\"https://www.siloamhospitals.com/image/x/300x200/2016/01/cardiology.png\">\n",
            "\t\t\t\t\t\t\t\t\t               \n",
            "\t\t\t\t\t\t\t\t\t                 <p>We create possibilities and one of it is to have a strong heart. Yes, We Can and You Can.</p>\n",
            "\t\t\t\t\t\t\t\t\t            </a>\n",
            "\t\t\t\t\t\t\t\t\t  \t</li>\n",
            "\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t  \t<li>\n",
            "\t\t\t\t\t\t\t\t\t\t\t  \t<a href=\"https://www.siloamhospitals.com/centre-of-excellence/emergency.html?EN\">\n",
            "\t\t\t\t\t\t\t\t\t               <span>Emergency</span>\n",
            "\t\t\t\t\t\t\t\t\t                <img width=\"100%\" class=\"imagecheck\" src=\"https://www.siloamhospitals.com/assets/img/no-pic.jpg\" data-src=\"https://www.siloamhospitals.com/image/x/300x200/2016/01/emergency.jpg\">\n",
            "\t\t\t\t\t\t\t\t\t               \n",
            "\t\t\t\t\t\t\t\t\t                 <p>Siloam Hospitals 24 hours Emergency Care guarantees you the highest level of skill and expertise.</p>\n",
            "\t\t\t\t\t\t\t\t\t            </a>\n",
            "\t\t\t\t\t\t\t\t\t  \t</li>\n",
            "\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t  \t<li>\n",
            "\t\t\t\t\t\t\t\t\t\t\t  \t<a href=\"https://www.siloamhospitals.com/centre-of-excellence/neurosciences.html?EN\">\n",
            "\t\t\t\t\t\t\t\t\t               <span>Neurosciences</span>\n",
            "\t\t\t\t\t\t\t\t\t                <img width=\"100%\" class=\"imagecheck\" src=\"https://www.siloamhospitals.com/assets/img/no-pic.jpg\" data-src=\"https://www.siloamhospitals.com/image/x/300x200/2016/01/neurosciences.jpg\">\n",
            "\t\t\t\t\t\t\t\t\t               \n",
            "\t\t\t\t\t\t\t\t\t                 <p>Meet our team of Neurology experts specialised in treating a variety of neurological diseases.</p>\n",
            "\t\t\t\t\t\t\t\t\t            </a>\n",
            "\t\t\t\t\t\t\t\t\t  \t</li>\n",
            "\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t  \t<li>\n",
            "\t\t\t\t\t\t\t\t\t\t\t  \t<a href=\"https://www.siloamhospitals.com/centre-of-excellence/oncology.html?EN\">\n",
            "\t\t\t\t\t\t\t\t\t               <span>Oncology</span>\n",
            "\t\t\t\t\t\t\t\t\t                <img width=\"100%\" class=\"imagecheck\" src=\"https://www.siloamhospitals.com/assets/img/no-pic.jpg\" data-src=\"https://www.siloamhospitals.com/image/x/300x200/2016/01/oncology.png\">\n",
            "\t\t\t\t\t\t\t\t\t               \n",
            "\t\t\t\t\t\t\t\t\t                 <p>Our team of Oncology specialists are here to help and provide you with the care you need.</p>\n",
            "\t\t\t\t\t\t\t\t\t            </a>\n",
            "\t\t\t\t\t\t\t\t\t  \t</li>\n",
            "\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t  \t<li>\n",
            "\t\t\t\t\t\t\t\t\t\t\t  \t<a href=\"https://www.siloamhospitals.com/centre-of-excellence/orthopaedics.html?EN\">\n",
            "\t\t\t\t\t\t\t\t\t               <span>Orthopaedics</span>\n",
            "\t\t\t\t\t\t\t\t\t                <img width=\"100%\" class=\"imagecheck\" src=\"https://www.siloamhospitals.com/assets/img/no-pic.jpg\" data-src=\"https://www.siloamhospitals.com/image/x/300x200/2016/02/orthopaedics.jpg\">\n",
            "\t\t\t\t\t\t\t\t\t               \n",
            "\t\t\t\t\t\t\t\t\t                 <p>Regain your mobility with the help of our team of world class orthopaedic specialists.</p>\n",
            "\t\t\t\t\t\t\t\t\t            </a>\n",
            "\t\t\t\t\t\t\t\t\t  \t</li>\n",
            "\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t  \t<li>\n",
            "\t\t\t\t\t\t\t\t\t\t\t  \t<a href=\"https://www.siloamhospitals.com/centre-of-excellence/urology.html?EN\">\n",
            "\t\t\t\t\t\t\t\t\t               <span>Urology</span>\n",
            "\t\t\t\t\t\t\t\t\t                <img width=\"100%\" class=\"imagecheck\" src=\"https://www.siloamhospitals.com/assets/img/no-pic.jpg\" data-src=\"https://www.siloamhospitals.com/image/x/300x200/2016/01/urology.png\">\n",
            "\t\t\t\t\t\t\t\t\t               \n",
            "\t\t\t\t\t\t\t\t\t                 <p>Whatever your urological condition, our Urology specialists will support you in gaining a better health condition.</p>\n",
            "\t\t\t\t\t\t\t\t\t            </a>\n",
            "\t\t\t\t\t\t\t\t\t  \t</li>\n",
            "\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t</ul>\n",
            "\t\t\t\t\t\t\t\t\t\t<div class=\"outside\">\n",
            "\t\t\t\t\t\t\t  \t\t\t\t<p><span class=\"bx-prev\"></span><span class=\"bx-next\"></span></p>\n",
            "\t\t\t\t\t\t\t  \t\t\t</div>\n",
            "\t\t\t\t\t\t\t  \t</div>\n",
            "\t\t\t\t\t\t  </div>\n",
            "\t\t\t  </div>\n",
            "  </section>\n",
            "</div>\n",
            "\n",
            "\n",
            "<div class=\"container-fluid\"  id=\"slide_techno\" style=\"display: none;\">\n",
            "  \t\t\t<section >\n",
            "  \t\t<div class=\"row\">\n",
            "  \t\t\t\t\t<div class=\"col-md-12\">\n",
            "  \t\t\t\t\t\t<h2 class=\"title\">\n",
            "       Explore Us    </h2>\n",
            "  \t\t\t\t\t\t<div id=\"techno\" class=\"carousel slide\" data-ride=\"carousel\">\n",
            "        <div class=\"carousel-inner\" role=\"listbox\">\n",
            "        \t        \t<div class=\"item active\">\n",
            "        \t\t<div align=\"right\">\n",
            "\t            <img class=\"image-rad\" src=\"https://www.siloamhospitals.com/image/x/500x400/2016/04/14618943280.jpg\" alt=\"Medical Check Up - What & How\">\n",
            "\t            <div class=\"carousel-caption\">\n",
            "\t              <a href=\"https://www.siloamhospitals.com/whats-new/read/medical-check-up-what-how.html\">\n",
            "\t              <p style=\"max-width: 180px; padding-right: 10px;\">Medical Check Up - What & How</p>\n",
            "\t              <br/>\n",
            "\t                More <span class=\"more-icon\"></span>\n",
            "\t              </a>\n",
            "\t            </div>\n",
            "\t            </div>\n",
            "          \t</div>\n",
            "          \t        \t<div class=\"item \">\n",
            "        \t\t<div align=\"right\">\n",
            "\t            <img class=\"image-rad\" src=\"https://www.siloamhospitals.com/image/x/500x400/2016/04/14612052960.jpg\" alt=\"Career With Siloam\">\n",
            "\t            <div class=\"carousel-caption\">\n",
            "\t              <a href=\"https://www.siloamhospitals.com/whats-new/read/career-with-siloam.html\">\n",
            "\t              <p style=\"max-width: 180px; padding-right: 10px;\">Career With Siloam</p>\n",
            "\t              <br/>\n",
            "\t                More <span class=\"more-icon\"></span>\n",
            "\t              </a>\n",
            "\t            </div>\n",
            "\t            </div>\n",
            "          \t</div>\n",
            "          \t        </div>\n",
            "        <!-- Indicators -->\n",
            "\t\t<ol class=\"carousel-indicators\">\n",
            "\t\t\t\t\t    <li data-target=\"#techno\" data-slide-to=\"0\" class=\"active\"></li>\n",
            "        \t\t\t    <li data-target=\"#techno\" data-slide-to=\"1\" class=\"\"></li>\n",
            "        \t\t\t</ol>\n",
            "\t\t<!-- End Indicator -->\n",
            "        <!-- Controls -->\n",
            "        <!-- <a class=\"left carousel-control\" href=\"#techno\" role=\"button\" data-slide=\"prev\">\n",
            "          <i class=\"fa fa-chevron-left\"></i>\n",
            "        </a>\n",
            "        <a class=\"right carousel-control\" href=\"#techno\" role=\"button\" data-slide=\"next\">\n",
            "           <i class=\"fa fa-chevron-right\"></i>\n",
            "        </a> -->\n",
            "    </div>\n",
            "  \t\t\t\t\t</div>\n",
            "  \t\t</div>\n",
            "  </section>\n",
            "</div>\n",
            "\n",
            "\n",
            "\n",
            "<div class=\"container-fluid\"  id=\"slide_instagram\" >\n",
            "  <style>\n",
            "\tsection.instagram .title::before {\n",
            "\t\tbackground: #23246c;\n",
            "\n",
            "\t}\n",
            "\tsection.instagram h2 {\n",
            "\t\t\t\tcolor: #23246c;\n",
            "\t}\n",
            "</style>\n",
            "  \t<section class=\"instagram\"> \n",
            "\t  \t<div class=\"row\">\n",
            "\t\t\t<div class=\"col-md-2\" >\n",
            "\t\t\t      <h2 class=\"title\" >\n",
            "\t\t\t        Follow our <br/>\n",
            "\t\t\t        Instagram \n",
            "\t\t\t        </h2>\n",
            "\t\t\t  </div>\n",
            "\t\t  \t  <div class=\"col-md-10\">\n",
            "\t\t\t\t    <div id=\"instagram\" class=\"carousel slide carousel-slide\" data-ride=\"carousel\">\n",
            "\t\t\t\t    \t<ul class=\"instagram-bx\">\n",
            "\n",
            "\t  \t\n",
            "\t  \t\n",
            "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li>\n",
            "\t\t\t\t\t\t\t\n",
            "\t\t\t\t\t\t\t\t\t  \t\t<a class=\"instagram-unit\" target=\"blank\" href=\"http://instagram.com/siloamhospitals/\">\n",
            "\t\t\t\t\t\t\t\t\t\t        <img src=\"https://scontent.cdninstagram.com/vp/ba2f0d1aea5b7d41f432a402405a3a6e/5B937D3C/t51.2885-15/s320x320/e15/32147268_2052743888381061_227741804806537216_n.jpg\" alt=\".\n",
            "Diperkirakan pada tahun 2017, angka kematian ibu di Indonesia berada di kisaran 259 hingga 305 per 100 ribu kelahiran. Angka ini masih jauh dari target yakni 102 per 100 ribu kelahiran. Hal tersebut diperkirakan terjadi karena masih terbatasnya sarana dan minimnya edukasi, terutama bagi ibu hamil yang berada di pelosok Indonesia.\n",
            ".\n",
            "Ketahui juga beberapa penyakit yang biasa diidap oleh ibu hamil berikut ini::\n",
            "- Anemia\n",
            "Terjadi karena pola makan yang tidak memerhatikan asupan nutrisi terutama zat besi.\n",
            "- Diabetes Gestasional\n",
            "Terjadi karena faktor hormon pada ibu hamil.\n",
            "- Preklamsia \n",
            "Ditandai dengan tekanan darah tinggi yang menyebabkan kurangnya aliran darah ke plasenta sehingga janin kekurangan nutrisi.\n",
            ".\n",
            "#SilioamHospitals\n",
            "#HealthcareExcellence\n",
            "#Kehamilan\n",
            "#PenyakitKehamilan\" width=\"100%\" height=\"auto\" />\t\t\t\t\t\t\t\n",
            "\t\t\t\t\t\t\t            </a>\n",
            "\t\t\t\t\t\t\t\t\t  \t</li>\n",
            "\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<li>\n",
            "\t\t\t\t\t\t\t\n",
            "\t\t\t\t\t\t\t\t\t  \t\t<a class=\"instagram-unit\" target=\"blank\" href=\"http://instagram.com/siloamhospitals/\">\n",
            "\t\t\t\t\t\t\t\t\t\t        <img src=\"https://scontent.cdninstagram.com/vp/f97ecfdfd9fbec9f44114456421a33bc/5B90E317/t51.2885-15/s320x320/e15/31973750_470122920090613_3247572055524114432_n.jpg\" alt=\".\n",
            "Berbagai pertanyaan sering muncul terlebih ketika seorang wanita sedang berada di masa kehamilan, seperti apakah ibu hamil boleh mengonsumsi sushi, minum kopi, dan masih banyak lagi.\n",
            ".\n",
            "Namun, tahukah Anda apa saja hal yang tidak boleh dilakukan di masa kehamilan?\n",
            ".\n",
            "Yuk, share jawaban Anda di kolom komentar!\n",
            ".\n",
            "#SiloamHospitals\n",
            "#HealthcareExcellence\n",
            "#Kehamilan\" width=\"100%\" height=\"auto\" />\t\t\t\t\t\t\t\n",
            "\t\t\t\t\t\t\t            </a>\n",
            "\t\t\t\t\t\t\t\t\t  \t</li>\n",
            "\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<li>\n",
            "\t\t\t\t\t\t\t\n",
            "\t\t\t\t\t\t\t\t\t  \t\t<a class=\"instagram-unit\" target=\"blank\" href=\"http://instagram.com/siloamhospitals/\">\n",
            "\t\t\t\t\t\t\t\t\t\t        <img src=\"https://scontent.cdninstagram.com/vp/bc214f3eb6422d752dc3fa1c14cc422f/5B93104B/t51.2885-15/s320x320/e15/31779333_168225760518540_8524142960109944832_n.jpg\" alt=\".\n",
            "Banyak kemungkinan dapat terjadi di sekitar Anda. Kini saatnya untuk Anda lebih sigap menghadapi situasi darurat seperti stroke, serangan jantung, dan kecelakaan.\n",
            ".\n",
            "Demi membantu Anda menghadapi situasi tersebut, Siloam Hospitals menyediakan layanan ambulans 24 jam (1-500-911) yang siap membantu Anda dalam menangani berbagai macam kasus darurat.\n",
            ".\n",
            "#SaveToSave\n",
            "#SiloamHospitals\n",
            "#HealthcareExcellence\n",
            "#GawatDarurat\n",
            "#Ambulans\" width=\"100%\" height=\"auto\" />\t\t\t\t\t\t\t\n",
            "\t\t\t\t\t\t\t            </a>\n",
            "\t\t\t\t\t\t\t\t\t  \t</li>\n",
            "\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<li>\n",
            "\t\t\t\t\t\t\t\n",
            "\t\t\t\t\t\t\t\t\t  \t\t<a class=\"instagram-unit\" target=\"blank\" href=\"http://instagram.com/siloamhospitals/\">\n",
            "\t\t\t\t\t\t\t\t\t\t        <img src=\"https://scontent.cdninstagram.com/vp/34c902f701cd6f8bb9527ef680e4615c/5B7ED0C6/t51.2885-15/s320x320/e35/31988231_2036749073312248_8407311126580166656_n.jpg\" alt=\".\n",
            "Selamat kepada para pemenang Nobar Siloam Hospitals Photo Competition.\n",
            ".\n",
            "Yuk, lihat siapa saja pemenangnya dengan slide gambar di atas.\n",
            ".\n",
            "#SiloamHospitals\n",
            "#HealthcareExcellence\n",
            "#NontonBareng\n",
            "#NobarSiloam\n",
            "#ThisIsOurTeam\" width=\"100%\" height=\"auto\" />\t\t\t\t\t\t\t\n",
            "\t\t\t\t\t\t\t            </a>\n",
            "\t\t\t\t\t\t\t\t\t  \t</li>\n",
            "\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<li>\n",
            "\t\t\t\t\t\t\t\n",
            "\t\t\t\t\t\t\t\t\t  \t\t<a class=\"instagram-unit\" target=\"blank\" href=\"http://instagram.com/siloamhospitals/\">\n",
            "\t\t\t\t\t\t\t\t\t\t        <img src=\"https://scontent.cdninstagram.com/vp/625d3ae217640c45974a749d750fb319/5B8EBB3E/t51.2885-15/s320x320/e15/32121770_2035933376726133_1575791915712905216_n.jpg\" alt=\".\n",
            "Kehamilan adalah suatu anugerah yang harus dijaga dengan baik. Namun, ada kalanya ibu hamil merasa cemas dengan segala aktivitas yang dilakukannya, terlebih pada masa awal kehamilan.\n",
            ".\n",
            "Oleh karena itu, mari ketahui bersama beberapa hal yang boleh dilakukan di masa kehamilan di bawah ini, termasuk beberapa hal yang terkadang dicemaskan:\n",
            ".\n",
            "- Berolahraga\n",
            "- Memiliki tidur yang cukup\n",
            "- Mengonsumsi makanan bergizi seimbang\n",
            "- Berhubungan intim\n",
            ".\n",
            "#SiloamHospitals\n",
            "#HealthcareExcellence\n",
            "#Kehamilan\" width=\"100%\" height=\"auto\" />\t\t\t\t\t\t\t\n",
            "\t\t\t\t\t\t\t            </a>\n",
            "\t\t\t\t\t\t\t\t\t  \t</li>\n",
            "\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<li>\n",
            "\t\t\t\t\t\t\t\n",
            "\t\t\t\t\t\t\t\t\t  \t\t<a class=\"instagram-unit\" target=\"blank\" href=\"http://instagram.com/siloamhospitals/\">\n",
            "\t\t\t\t\t\t\t\t\t\t        <img src=\"https://scontent.cdninstagram.com/vp/be749f99ee67750fa982dbcc9ec49398/5B0818B6/t51.2885-15/s320x320/e35/30930173_113901229491641_5771003558266667008_n.jpg\" alt=\".\n",
            "Bibir sumbing dan celah langit-langit mulut adalah suatu kelainan yang dapat dikoreksi. Namun, mulai usia berapakah penanganan bibir sumbing dan celah langit-langit mulut dapat dilakukan?\n",
            ".\n",
            "Yuk, tulis jawaban Anda di kolom komentar. .\n",
            "#SiloamHospitals\n",
            "#HealthcareExcellence\n",
            "#BibirSumbing\n",
            "#CelahLangitLangit\n",
            "#TriviaQuiz\" width=\"100%\" height=\"auto\" />\t\t\t\t\t\t\t\n",
            "\t\t\t\t\t\t\t            </a>\n",
            "\t\t\t\t\t\t\t\t\t  \t</li>\n",
            "\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<li>\n",
            "\t\t\t\t\t\t\t\n",
            "\t\t\t\t\t\t\t\t\t  \t\t<a class=\"instagram-unit\" target=\"blank\" href=\"http://instagram.com/siloamhospitals/\">\n",
            "\t\t\t\t\t\t\t\t\t\t        <img src=\"https://scontent.cdninstagram.com/vp/b929cbe7c8fdbb6574428c46485fb8bf/5B087975/t51.2885-15/s320x320/e35/32821216_195533287747481_5217407231867224064_n.jpg\" alt=\".\n",
            "Kelainan bibir sumbing dan celah langit-langit mulut merupakan salah satu kelainan pada bayi yang umum terjadi, dengan kurang lebih 1:600 kelahiran yang terjadi di Indonesia.\n",
            ".\n",
            "Hingga saat ini belum diketahui secara pasti, apa faktor risiko yang menyebabkan kelainan tersebut terjadi. Namun, pada umumnya faktor tersebut dapat meliputi beberapa hal seperti pada video berikut ini.\n",
            ".\n",
            "#SiloamHospitals\n",
            "#HealthcareExcellence\n",
            "#BibirSumbing\n",
            "#CelahLangitLangit\" width=\"100%\" height=\"auto\" />\t\t\t\t\t\t\t\n",
            "\t\t\t\t\t\t\t            </a>\n",
            "\t\t\t\t\t\t\t\t\t  \t</li>\n",
            "\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<li>\n",
            "\t\t\t\t\t\t\t\n",
            "\t\t\t\t\t\t\t\t\t  \t\t<a class=\"instagram-unit\" target=\"blank\" href=\"http://instagram.com/siloamhospitals/\">\n",
            "\t\t\t\t\t\t\t\t\t\t        <img src=\"https://scontent.cdninstagram.com/vp/579aade615799c544295a2f63845b730/5B84A9BC/t51.2885-15/s320x320/e15/31711555_901142483405700_1955646021736333312_n.jpg\" alt=\".\n",
            "drg. Andi Setiawan Budihardja, SpBM(K) merupakan seorang dokter spesialis bedah mulut & maksilofasial yang menyelesaikan pendidikan dokter giginya di Universitas Trisakti, Jakarta, pada tahun 2001 dan pendidikan spesialis bedah mulut & maksilofasial di Universitas Ruhr Bochum, Jerman, pada 2007 silam.\n",
            ".\n",
            "Bagi drg. Andi yang kini berpraktik di Siloam Hospitals Lippo Village, beliau mulai terinspirasi untuk menjadi dokter saat melihat langsung orangtuanya yang mengobati pasien dan melihat banyaknya pasien yang membutuhkan pertolongan.\n",
            ".\n",
            "Menurutnya, sangatlah penting untuk menangani pasien bibir sumbing dan celah langit-langit mulut secara tepat dan baik, demi mencegah berbagai komplikasi seperti gangguan pendengaran, ganggguan dalam pertumbuhan gigi, kesulitan dalam mengonsumsi makanan, dan kesulitan dalam bersosialisasi serta berkomunikasi.\n",
            ".\n",
            "#SiloamHospitals\n",
            "#HealthcareExcellence\n",
            "#BibirSumbing\n",
            "#CelahLangitLangitMulut\n",
            "#SiloamHospitalsLippoVillage\n",
            "#DokterSehatKita\" width=\"100%\" height=\"auto\" />\t\t\t\t\t\t\t\n",
            "\t\t\t\t\t\t\t            </a>\n",
            "\t\t\t\t\t\t\t\t\t  \t</li>\n",
            "\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<li>\n",
            "\t\t\t\t\t\t\t\n",
            "\t\t\t\t\t\t\t\t\t  \t\t<a class=\"instagram-unit\" target=\"blank\" href=\"http://instagram.com/siloamhospitals/\">\n",
            "\t\t\t\t\t\t\t\t\t\t        <img src=\"https://scontent.cdninstagram.com/vp/89ce0a5f5e3d6e699ac8fba9777129da/5B9F0F57/t51.2885-15/s320x320/e15/32025136_174187643196195_800262521616334848_n.jpg\" alt=\".\n",
            "Bibir sumbing adalah kondisi dimana seorang bayi terlahir dengan celah di bibir bagian atas. Celah tersebut bisa terdapat hanya pada bagian bibir saja ataupun celah hingga bagian gusi dan tulang rahang. Pada sebagian bayi, celah ini dapat meliputi seluruh bagian bibir (complete cleft) atau hanya meliputi sebagian bibir saja (incomplete cleft).\n",
            ".\n",
            "Sedangkan, celah langit-langit mulut adalah suatu kelainan di mana terdapat celah pada bagian langit-langit mulut. Kelainan ini dapat terjadi bersamaan pada penderita kelainan celah bibir ataupun tanpa disertai kelainan celah bibir.\n",
            ".\n",
            "Kini telah tersedia juga Klinik Celah Bibir dan Langit-Langit Mulut di Siloam Hospitals Lippo Village.\n",
            "Untuk informasi lebih lanjut, dapat menghubungi: (021) 80646900\n",
            ".\n",
            "#SiloamHospitals\n",
            "#HealthcareExcellence\n",
            "#BibirSumbing\n",
            "#CelahLangitLangit\" width=\"100%\" height=\"auto\" />\t\t\t\t\t\t\t\n",
            "\t\t\t\t\t\t\t            </a>\n",
            "\t\t\t\t\t\t\t\t\t  \t</li>\n",
            "\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<li>\n",
            "\t\t\t\t\t\t\t\n",
            "\t\t\t\t\t\t\t\t\t  \t\t<a class=\"instagram-unit\" target=\"blank\" href=\"http://instagram.com/siloamhospitals/\">\n",
            "\t\t\t\t\t\t\t\t\t\t        <img src=\"https://scontent.cdninstagram.com/vp/0e3c64635c89c20066b0ab6d241222c3/5B7F566D/t51.2885-15/s320x320/e35/31941425_1626966760753628_6143170291305545728_n.jpg\" alt=\".\n",
            "Siloam Hospitals mempersembahkan Paket Hardiknas karena masa depan yang cerah tercermin dari bangsa yang sehat. Paket tersebut mencakup:\n",
            ".\n",
            "CT Coronary Calcium Scan*\n",
            "(termasuk Dokter Spesialis Jantung)\n",
            "Rp 199.000\n",
            "Khusus untuk para guru/dosen: Rp 150.000\n",
            "(Para guru/dosen diharapkan untuk membawa Surat Keterangan Kerja dan Kartu ID)\n",
            ".\n",
            "Syarat dan ketentuan berlaku:\n",
            "- Berlaku hingga 31 Mei 2018\n",
            "- Tidak dapat digabungkan dengan paket lainnya\n",
            "- Berlaku di cabang Siloam Hospitals berikut:\n",
            "-\tRumah Sakit Siloam Asri\n",
            "-\tRumah Sakit Siloam Bekasi Timur\n",
            "-\tRumah Sakit Siloam Dhirga Surya\n",
            "-\tRumah Sakit Jantung Diagram\n",
            "-\tRumah Sakit Siloam Yogyakarta\n",
            "-\tSiloam Hospitals Denpasar\n",
            "-\tSiloam Hospitals Bogor\n",
            "-\tSiloam Hospitals Lippo Cikarang\n",
            "-\tMRCCC Siloam Hospitals Semanggi\n",
            "-\tSiloam Hospitals Kebon Jeruk\n",
            "- \tSiloam Hospitals Kupang\n",
            "-\tSiloam Hospitals TB Simatupang\n",
            "-\tSiloam Hospitals Purwakarta\n",
            "-\tSiloam Hospitals Surabaya\n",
            "-\tSiloam Hospitals Lippo Village\n",
            "-\tSiloam Hospitals Makassar\n",
            "-\tSiloam Hospitals Manado\n",
            "-\tSiloam Hospitals Jambi\n",
            "-\tSiloam Hospitals Jember\n",
            "-\tSiloam Sriwijaya Palembang\n",
            ".\n",
            "*Pemeriksaan ini adalah deteksi dini untuk melihat indikasi RISIKO penyakit jantung.\n",
            ".\n",
            "Untuk informasi dan pendaftaran: 1-500-181\n",
            ".\n",
            "#SiloamHospitals \n",
            "#HealthcareExcellence \n",
            "#Jantung \n",
            "#PaketHardiknas \n",
            "#Hardiknas2018\" width=\"100%\" height=\"auto\" />\t\t\t\t\t\t\t\n",
            "\t\t\t\t\t\t\t            </a>\n",
            "\t\t\t\t\t\t\t\t\t  \t</li>\n",
            "\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\t\t<li>\n",
            "\t\t\t\t\t\t\t\n",
            "\t\t\t\t\t\t\t\t\t  \t\t<a class=\"instagram-unit\" target=\"blank\" href=\"http://instagram.com/siloamhospitals/\">\n",
            "\t\t\t\t\t\t\t\t\t\t        <img src=\"https://scontent.cdninstagram.com/vp/a4ff3c1bf66be368b199b0e2027d1247/5B8BBC34/t51.2885-15/s320x320/e15/32010211_931900340323590_1555331662177370112_n.jpg\" alt=\".\n",
            "Siloam Hospitals mengucapkan selamat menunaikan ibadah puasa di bulan suci Ramadhan bagi Anda yang menjalankan.\n",
            ".\n",
            "Mari sambut bulan yang suci ini dengan penuh keikhlasan, serta jiwa dan raga yang sehat.\n",
            ".\n",
            "#SiloamHospitals\n",
            "#HealthcareExcellence\n",
            "#IbadahPuasa\n",
            "#Ramadhan2018\" width=\"100%\" height=\"auto\" />\t\t\t\t\t\t\t\n",
            "\t\t\t\t\t\t\t            </a>\n",
            "\t\t\t\t\t\t\t\t\t  \t</li>\n",
            "\t\t\t\t\t\t\t\t\t  \t\t\n",
            "\n",
            "\n",
            "\t\t\t\t\t</ul>\n",
            "\t\t\t\t\t<div class=\"outside\">\n",
            "\t\t\t\t\t  \t\t<p><span class=\"bx-prev-instagram\"></span><span class=\"bx-next-instagram\"></span></p>\n",
            "\t\t\t\t\t</div>\n",
            "\t\t\t    </div>\n",
            "\t\t\t  </div>\n",
            "\t\t</div>\n",
            "  \t</section>\n",
            "  \n",
            "  \n",
            "</div>\n",
            "\n",
            "\n",
            "\n",
            "<div class=\"container-fluid\"  id=\"whats-new\">\n",
            "<!-- UPDATE 13/6 -->\n",
            "  \t\t\t<section class=\"article-list\">\n",
            "\t\t\t  \t<div class=\"row\">\n",
            "\t\t\t  \t\t\t<div class=\"col-md-3 col-sm-3\">\n",
            "\t\t\t          <h2 class=\"title\">\n",
            "\t\t\t           What's New\t\t\t          </h2>\n",
            "\t\t\t  </div>\n",
            "\t\t\t  \t\t\t<div class=\"col-md-9 col-sm-9\">\n",
            "\t\t\t\n",
            "\t\t\t      <!-- Nav tabs -->\n",
            "\t\t\t      <ul class=\"nav nav-tabs\" role=\"tablist\">\n",
            "\t\t\t      \t\t\t\t        <li role=\"presentation\" class=\"\">\n",
            "\t\t\t        \t<a href=\"#silver-magazine-3-content\" aria-controls=\"silver\" role=\"tab\" data-toggle=\"tab\">Silver Magazine</a>\n",
            "\t\t\t        </li>\n",
            "\t\t\t        \t\t\t        <li role=\"presentation\" class=\"active\">\n",
            "\t\t\t        \t<a href=\"#advertorial-3-content\" aria-controls=\"silver\" role=\"tab\" data-toggle=\"tab\">Advertorial</a>\n",
            "\t\t\t        </li>\n",
            "\t\t\t        \t\t\t        <li role=\"presentation\" >\n",
            "\t\t\t        \t<a href=\"#video-content\" aria-controls=\"video\" role=\"tab\" data-toggle=\"tab\">Video</a>\n",
            "\t\t\t        </li>\n",
            "\t\t\t      </ul>\n",
            "\t\t\t\n",
            "\t\t\t      <!-- Tab panes -->\n",
            "\t\t\t      <div class=\"tab-content\">\n",
            "\t\t\t\t      \n",
            "\t\t\t\t      \t\t\t\t      \n",
            "\t\t\t      \t\t\t\t    \t<div role=\"tabpanel\" class=\"tab-pane \" id=\"silver-magazine-3-content\">\n",
            "\t\t\t    \t\t\n",
            "\t\t\t    \t\t\t\t\t            <div class=\"lg-article col-md-6 col-sm-6\">\n",
            "\t\t\t                <span class=\"date_posted\">20 Dec 2017</span> \n",
            "\t\t\t                <a href=\"https://www.siloamhospitals.com/admin/assets/uploads/2017/18/Silver Mag Nov-Des 2017.pdf\" target=\"_blank\">\n",
            "\t\t\t                \t<img src=\"https://www.siloamhospitals.com/image/x/300x200/2017/08/DCP-SILVER-NOV-DEC2017_.jpg\">\n",
            "\t\t\t\t\t\t\t\t<h3>Nov - Des '17</h3>\n",
            "\t\t\t\t\t\t\t</a>\n",
            "\t\t\t                <p>\n",
            "\t\t\t                  \t\t\t                </p>\n",
            "\t\t\t            </div>\n",
            "\t\t\t          \t<div class=\"col-md-6 col-sm-6\">\n",
            "\t\t\t                <ul>\n",
            "\t\t\t\t\t\t\t\t\t                \t\t\t            \t\t\t                \t\t\t                  \t<li> \n",
            "\t\t\t                    \t<span class=\"date_posted\">23 Oct 2017</span> \n",
            "\t\t\t                    \t<a href=\"https://www.siloamhospitals.com/admin/assets/uploads/2017/08/15023354560sep-oct.pdf\" target=\"_blank\">Sep - Oct'17</a> \n",
            "\t\t\t                  \t</li>\n",
            "\t\t\t                \t\t\t            \t\t\t                \t\t\t                  \t<li> \n",
            "\t\t\t                    \t<span class=\"date_posted\">10 Aug 2017</span> \n",
            "\t\t\t                    \t<a href=\"https://www.siloamhospitals.com/admin/assets/uploads/2017/08/15023354560.pdf\" target=\"_blank\">Jul - Aug'17\u200B</a> \n",
            "\t\t\t                  \t</li>\n",
            "\t\t\t                \t\t\t            \t\t\t                \t\t\t                  \t<li> \n",
            "\t\t\t                    \t<span class=\"date_posted\">04 Aug 2017</span> \n",
            "\t\t\t                    \t<a href=\"https://www.siloamhospitals.com/admin/assets/uploads/2017/08/15018272680.pdf\" target=\"_blank\"> May – Jun’17</a> \n",
            "\t\t\t                  \t</li>\n",
            "\t\t\t                \t\t\t            \t\t\t                \t\t\t                  \t<li> \n",
            "\t\t\t                    \t<span class=\"date_posted\">22 Mar 2017</span> \n",
            "\t\t\t                    \t<a href=\"https://www.siloamhospitals.com/admin/assets/uploads/2017/03/14901767330.pdf\" target=\"_blank\">Mar – Apr'17</a> \n",
            "\t\t\t                  \t</li>\n",
            "\t\t\t                \t\t\t            \t\t\t              \t</ul>\n",
            "\t\t\t              \t\t\t\t              \t<a href=\"https://www.siloamhospitals.com/whats-new.html\" class=\"more\">\n",
            "\t\t\t                View All Articles <span class=\"more-icon-white\"></span>\n",
            "\t\t\t              \t</a>\n",
            "\t\t\t              \t\t\t\t            </div>\n",
            "\t\t\t            \t\t\t    \t</div>\n",
            "\t\t\t    \t\t\t\t    \t<div role=\"tabpanel\" class=\"tab-pane active\" id=\"advertorial-3-content\">\n",
            "\t\t\t    \t\t\n",
            "\t\t\t    \t\t\t\t\t            <div class=\"lg-article col-md-6 col-sm-6\">\n",
            "\t\t\t                <span class=\"date_posted\">25 Apr 2018</span> \n",
            "\t\t\t                <a href=\"https://www.siloamhospitals.com/whats-new/read/mengenal-mimisan-dan-cara-menanganinya.html\">\n",
            "\t\t\t                \t<img src=\"https://www.siloamhospitals.com/image/x/300x200/2017/18/300x200-maret18008.jpg\">\n",
            "\t\t\t\t\t\t\t\t<h3>Mengenal Mimisan Dan Cara Menanganinya</h3>\n",
            "\t\t\t\t\t\t\t</a>\n",
            "\t\t\t                <p>\n",
            "\t\t\t                  \t\t\t                </p>\n",
            "\t\t\t            </div>\n",
            "\t\t\t          \t<div class=\"col-md-6 col-sm-6\">\n",
            "\t\t\t                <ul>\n",
            "\t\t\t\t\t\t\t\t\t                \t\t\t            \t\t\t                \t\t\t                  \t<li> \n",
            "\t\t\t                    \t<span class=\"date_posted\">25 Apr 2018</span> \n",
            "\t\t\t                    \t<a href=\"https://www.siloamhospitals.com/whats-new/read/4-cara-kurangi-risiko-radang-tenggorokan.html\">4 Cara Kurangi Risiko Radang Tenggorokan</a> \n",
            "\t\t\t                  \t</li>\n",
            "\t\t\t                \t\t\t            \t\t\t                \t\t\t                  \t<li> \n",
            "\t\t\t                    \t<span class=\"date_posted\">25 Apr 2018</span> \n",
            "\t\t\t                    \t<a href=\"https://www.siloamhospitals.com/whats-new/read/waspadai-gejala-awal-kanker-paru.html\">Waspadai Gejala Awal Kanker Paru</a> \n",
            "\t\t\t                  \t</li>\n",
            "\t\t\t                \t\t\t            \t\t\t                \t\t\t                  \t<li> \n",
            "\t\t\t                    \t<span class=\"date_posted\">25 Apr 2018</span> \n",
            "\t\t\t                    \t<a href=\"https://www.siloamhospitals.com/whats-new/read/8-langkah-utama-mengatasi-malnutrisi-pada-lansia.html\">8 langkah utama mengatasi malnutrisi pada lansia</a> \n",
            "\t\t\t                  \t</li>\n",
            "\t\t\t                \t\t\t            \t\t\t                \t\t\t                  \t<li> \n",
            "\t\t\t                    \t<span class=\"date_posted\">25 Apr 2018</span> \n",
            "\t\t\t                    \t<a href=\"https://www.siloamhospitals.com/whats-new/read/6-pola-hidup-sehat-cegah-kanker-payudara.html\">6 Pola Hidup Sehat Cegah Kanker Payudara</a> \n",
            "\t\t\t                  \t</li>\n",
            "\t\t\t                \t\t\t            \t\t\t              \t</ul>\n",
            "\t\t\t              \t\t\t\t              \t<a href=\"https://www.siloamhospitals.com/news-events/advertorial-3.html\" class=\"more\">\n",
            "\t\t\t                View All Articles <span class=\"more-icon-white\"></span>\n",
            "\t\t\t              \t</a>\n",
            "\t\t\t              \t\t\t\t            </div>\n",
            "\t\t\t            \t\t\t    \t</div>\n",
            "\t\t\t    \t\t\t\t    \t\n",
            "\t\t\t    \t<div role=\"tabpanel\" class=\"tab-pane \" id=\"video-content\">\n",
            "\t\t\t\t\t\t\n",
            "\t\t\t\t\t   \t<ul>\n",
            "\t\t\t\t    \t\t\t\t\t\t   \t\t\t\t\t\t            <div class=\"lg-article col-md-6 col-sm-6\">\n",
            "\t\t\t\t\t                <span class=\"date_posted\">11 Apr 2018</span> \n",
            "\t\t\t\t\t                <a href=\"https://www.siloamhospitals.com/news-events/watch/hari-kartini-biarkan-mereka-terus-berkarya-2.html\">\n",
            "\t\t\t\t\t                \t<img src=\"https://www.siloamhospitals.com/image/x/300x200/2017/18/kartini-cover-2.jpg\">\n",
            "\t\t\t\t\t\t\t\t\t\t<h3>Hari Kartini Biarkan Mereka Terus Berkarya</h3>\n",
            "\t\t\t\t\t\t\t\t\t</a>\n",
            "\t\t\t\t\t              \n",
            "\t\t\t\t\t            </div>\n",
            "\t\t\t          \t<div class=\"col-md-6 col-sm-6\">\n",
            "\t\t\t                <ul>\n",
            "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t   \t\t\t\t\t\t   \t\t\t\t\t\t\t\t\t\t\t\t\t<li>\n",
            "\t\t\t\t\t\t\t<span class=\"date_posted\">\n",
            "\t\t\t\t\t\t\tTue, 28 Mar 2017\t\t\t\t\t\t\t</span>\n",
            "\t\n",
            "\t\t                \t<a href=\"https://www.siloamhospitals.com/news-events/watch/4-fase-penyempitan-pembuluh-darah-penyebab-penyakit-jantung-koroner.html\">       \n",
            "\t\t\t\t\t\t\t\t4 Fase Penyempitan Pembuluh Darah Penyebab Penyakit Jantung Koroner\t                      \t</a>\n",
            "\t\t\t\t\t  \t</li>\n",
            "\t\t\t\t\t  \t\t\t\t\t\t   \t\t\t\t\t\t   \t\t\t\t\t\t\t\t\t\t\t\t\t<li>\n",
            "\t\t\t\t\t\t\t<span class=\"date_posted\">\n",
            "\t\t\t\t\t\t\tTue, 21 Mar 2017\t\t\t\t\t\t\t</span>\n",
            "\t\n",
            "\t\t                \t<a href=\"https://www.siloamhospitals.com/news-events/watch/pertolongan-pertama-luka-bakar-ringan-pada-anak.html\">       \n",
            "\t\t\t\t\t\t\t\tPertolongan Pertama Luka Bakar Ringan Pada Anak\t                      \t</a>\n",
            "\t\t\t\t\t  \t</li>\n",
            "\t\t\t\t\t  \t\t\t\t\t\t   \t\t\t\t\t\t   \t\t\t\t\t\t\t\t\t\t\t\t\t<li>\n",
            "\t\t\t\t\t\t\t<span class=\"date_posted\">\n",
            "\t\t\t\t\t\t\tMon, 13 Mar 2017\t\t\t\t\t\t\t</span>\n",
            "\t\n",
            "\t\t                \t<a href=\"https://www.siloamhospitals.com/news-events/watch/beberapa-langkah-menjaga-kesehatan-ginjal.html\">       \n",
            "\t\t\t\t\t\t\t\tBeberapa Langkah Menjaga Kesehatan Ginjal\t                      \t</a>\n",
            "\t\t\t\t\t  \t</li>\n",
            "\t\t\t\t\t  \t\t\t\t\t\t   \t\t\t\t\t\t   \t\t\t\t\t\t\t\t\t\t\t\t\t<li>\n",
            "\t\t\t\t\t\t\t<span class=\"date_posted\">\n",
            "\t\t\t\t\t\t\tThu, 09 Mar 2017\t\t\t\t\t\t\t</span>\n",
            "\t\n",
            "\t\t                \t<a href=\"https://www.siloamhospitals.com/news-events/watch/apakah-dengan-melakukan-mastektomi-akan-terbebas-total-dari-kanker-payudara.html\">       \n",
            "\t\t\t\t\t\t\t\tApakah Dengan Melakukan Mastektomi Akan Terbebas Total Dari Kanker Payudara\t                      \t</a>\n",
            "\t\t\t\t\t  \t</li>\n",
            "\t\t\t\t\t  \t\t\t\t\t\t   \t\t\t\t\t\t   \t</ul>\n",
            "\t\t\t\t\t   \t<a href=\"https://www.siloamhospitals.com/news-events/video.html\" class=\"more\">\n",
            "\t\t\t                View All Articles <span class=\"more-icon-white\"></span>\n",
            "\t\t\t              \t</a>\n",
            "\n",
            "\t\t\t\t    \t</div>\n",
            "\t\t\t\t    \t\n",
            "\t\t\t    \t</div>\n",
            "\t\t\t    \t\n",
            "\t\t\t\n",
            "\t\t\t    </div>\n",
            "\t\t\t  </div>\n",
            "\t\t\t</section>\n",
            "</div>\n",
            "\n",
            "\n",
            "\n",
            "\n",
            "<div class=\"container-fluid\"  style=\"padding: 0px;background: #23246c;\">\n",
            "\n",
            "</div> \t\n",
            "</div>\n",
            "\t\t<footer class=\"site-footer\">\n",
            "        <div class=\"container\">\n",
            "\t\t\t<div class=\"container-fluid\"  id=\"appointment\">\n",
            "\t\t\t  <section>\n",
            "\t\t\t    <div class=\"row\">\n",
            "\t\t\t     <!-- mod update  -->\n",
            "\t\t\t      <div class=\"col-md-3 col-sm-3\" id=\"footer\" >\n",
            "\t\t\t      \t\n",
            "\t\t\t      <a href=\"https://www.siloamhospitals.com/make-an-appointment.html\">\n",
            "\t\t\t      <span class=\"icon-calendar icon\">\n",
            "\t\t\t      </span>\n",
            "\t\t\t        <span class=\"text\">Make an<br/>Appointment</span>\n",
            "\t\t\t      </a>\n",
            "\t\t\t      </div>\n",
            "\t\t\t\n",
            "\t\t\t       <div class=\"col-md-3 col-sm-3\" id=\"footer\">\n",
            "\t\t\t        <a href=\"https://www.siloamhospitals.com/my-checkup.html\">\n",
            "\t\t\t        <span class=\"icon-checkup icon\">\n",
            "\t\t\t        </span>\n",
            "\t\t\t          <span class=\"text\">My <br>Checkup</span>\n",
            "\t\t\t        </a>\n",
            "\t\t\t      </div>\n",
            "\t\t\t\n",
            "\t\t\t       <div class=\"col-md-3 col-sm-3\" id=\"footer\">\n",
            "\t\t\t        <a href=\"https://www.siloamhospitals.com/doctors/find.html\">\n",
            "\t\t\t        <span class=\"icon-walk icon\">\n",
            "\t\t\t        </span>\n",
            "\t\t\t          <span class=\"text\">Find your<br>Doctors</span>\n",
            "\t\t\t        </a>\n",
            "\t\t\t      </div>\n",
            "\t\t\t\n",
            "\t\t\t        <div class=\"col-md-3 col-sm-3\" id=\"footer\">\n",
            "\t\t\t          <a href=\"https://www.siloamhospitals.com/health-library.html\">\n",
            "\t\t\t          <span class=\"icon-library icon\">\n",
            "\t\t\t          </span>\n",
            "\t\t\t            <span class=\"text\">Health<br>Library</span>\n",
            "\t\t\t          </a>\n",
            "\t\t\t      \t</div>\n",
            "\t\t\t\n",
            "\t\t\t      \t<!-- <div class=\"col-md-15 col-sm-3\">\n",
            "\t\t\t          <a href=\"#\">\n",
            "\t\t\t          <span class=\"icon-disab icon\">\n",
            "\t\t\t          </span>\n",
            "\t\t\t           <span class=\"text\">Refer a <br>\n",
            "\t\t\t            Patient</span>\n",
            "\t\t\t          </a>\n",
            "\t\t\t     \t</div> -->\n",
            "\t\t\t     \n",
            "\t\t\t    </div>\n",
            "\t\t\t  </section>\n",
            "\t\t\t</div>\n",
            "            <div class=\"row\">\n",
            "            \t<div class=\"row footer-img\">\n",
            "                  <div class=\"col-md-6 col-sm-6\">\n",
            "                    <div class=\"col-md-12\">\n",
            "                      <h6 align=\"left\">&nbsp;&nbsp;&nbsp;Achievements</h6>\n",
            "                    </div>\n",
            "                    <div class=\"col-md-12\" align=\"left\">\n",
            "                        <img src=\"https://www.siloamhospitals.com/assets/img/frost_footer.png\" alt=\"Indonesia Healthcare Services Provider of the Year\" title=\"Indonesia Healthcare Services Provider of the Year\"/><br/>\n",
            "                    \t<img src=\"https://www.siloamhospitals.com/assets/img/jci_footer.png\"/>\n",
            "                       \t\n",
            "                \t</div>\n",
            "                </div>\n",
            "                <div class=\"col-md-6 col-sm-6\">\n",
            "                  <div class=\"col-md-12\">\n",
            "                    <h6 align=\"left\">&nbsp;&nbsp;&nbsp;In Partnership With</h6>\n",
            "                  </div>\n",
            "                     <div class=\"col-md-12\" align=\"left\">\n",
            "                        <img src=\"https://www.siloamhospitals.com/assets/img/achivement/footer/lippo_footer.png\"/>\n",
            "                      \t<img src=\"https://www.siloamhospitals.com/assets/img/achivement/footer/uph_footer.png\"/><br/>\n",
            "                     \t<img src=\"https://www.siloamhospitals.com/assets/img/achivement/footer/mrin_footer.png\"/>\n",
            "                      \t<img src=\"https://www.siloamhospitals.com/assets/img/achivement/footer/gkci_footer.png\"/>\n",
            "                     </div>\n",
            "                  </div>\n",
            "                </div>\n",
            "            </div>\n",
            "            <div class=\"row\">\n",
            "              <div class=\"row footer-text\">\n",
            "                <div class=\"col-md-12\" align=\"center\">\n",
            "                  <ul>\n",
            "                  \t<li>\n",
            "                        <h6><a href=\"https://www.siloamhospitals.com/about-us.html\">About Us</a></h6>\n",
            "                    </li>\n",
            "                    <li>\n",
            "                        <h6><a href=\"https://www.siloamhospitals.com/investor-relations.html\">Investor Relations</a></h6>\n",
            "                    </li>\n",
            "                  \t<li>\n",
            "                        <h6><a href=\"https://www.siloamhospitals.com/news-events/media-coverage.html?EN\">News & Events</a></h6>\n",
            "                    </li>\n",
            "                      <li>\n",
            "                        <h6><a href=\"https://www.siloamhospitals.com/contact-us.html\">Contact Us</a></h6>\n",
            "                      </li>\n",
            "                      <li>\n",
            "                        <h6><a href=\"https://www.siloamhospitals.com/faq.html\">FAQ</a></h6>\n",
            "                      </li>\n",
            "                  </ul>\n",
            "                </div>\n",
            "                </div>\n",
            "              </div>\n",
            "            \n",
            "            <div class=\"row footer_copy\">\n",
            "              <div class=\"col-md-12\" align=\"center\">\n",
            "                <p>Copyright &copy; 2016. Siloam Hospitals Groups</p>\n",
            "              </div>\n",
            "            </div>\n",
            "          </div>\n",
            "\t\t</footer>\n",
            "\t\t<script type=\"text/javascript\">\n",
            "\t\t\tvar IMG_URL = \"https://www.siloamhospitals.com/assets/uploads/\";\n",
            "\t\t</script>\n",
            "    \t<script src=\"https://www.siloamhospitals.com/assets/js/vendor/jquery-1.7.2.min.js\"></script>\n",
            "    \t<!--<script src=\"https://www.siloamhospitals.com/assets/js/vendor/jquery-1.12.4.min.js\"></script>-->\n",
            "    \t<script src=\"https://www.siloamhospitals.com/assets/js/jquery.bxslider.min.js\"></script>\n",
            "    \t<script src=\"https://www.siloamhospitals.com/assets/js/vendor/bootstrap.js\"></script>\n",
            "        <script src=\"https://www.siloamhospitals.com/assets/js/bootstrap-select.js\"></script>\n",
            "        <script src=\"https://www.siloamhospitals.com/assets/js/vendor/bloodhound.min.js\"></script>\n",
            "        <script src=\"https://www.siloamhospitals.com/assets/js/vendor/typehead.min.js\"></script>\n",
            "        <script src=\"https://www.siloamhospitals.com/assets/js/main.js?time\"></script>\n",
            "        <script src=\"https://www.siloamhospitals.com/assets/js/custom.js?sa\"></script>\n",
            "        <script src=\"https://www.siloamhospitals.com/assets/js/find-doctor.js\"></script>\n",
            "        <script type=\"text/javascript\">\n",
            "\t        \n",
            "\t\t\t\t$(document).scroll(function() {\n",
            "\t\t\t \t   checkOffset();\n",
            "\t\t\t\t});\t        \n",
            "\t\t\t\tfunction checkOffset() {\n",
            "\t\t\t\t\tvar homeheight = $('.site-footer').offset().top;\t\n",
            "\t\t\t\t\t//alert(homeheight);\n",
            "\t\t\t\t\t\n",
            "\t\t\t\tif($('#appointment').offset().top , $('#appointment').height() > homeheight )\n",
            "\t\t\t\t\t$('#appointment').css('position', 'relative');\n",
            "\t\t\t\tif($(document).scrollTop() , window.innerHeight < $('.site-footer').offset().top)\n",
            "\t\t\t\t\t\t $('#appointment').css('position', 'fixed'); \n",
            "\n",
            "\t\t\t\t}\n",
            "\n",
            "\t\t\t\n",
            "\t\t</script>\n",
            "    </body>\n",
            "</html>\n" });
}
